"""Composable 3D printing agent backend."""

from .calibration import (
    CalibrationError,
    CalibrationInspection,
    CalibrationLimits,
    CalibrationReport,
    CalibrationResult,
    ColorAssignment,
    ColorMapping,
    InventoryColor,
    SourceColor,
    calibrate_3mf,
    geometry_only_3mf,
    inspect_3mf,
)
from .contracts import (
    ColorMatchAssignment,
    ColorMatchResponse,
    CreativeBrief,
    ModelRepairState,
    PrintabilityMetrics,
    PrintabilityReport,
    PrintAnalysisState,
    PrintFileState,
    SessionSnapshot,
    SessionStatus,
    SubworkflowStatus,
)
from .factory import create_agent
from .filament_inventory import (
    FilamentColorMapping,
    FilamentColorRecord,
    FilamentInventoryRepository,
    InventoryConfigurationError,
    InventoryDataError,
)
from .service import ThreeDPrintAgent

__all__ = [
    "CreativeBrief",
    "ModelRepairState",
    "PrintAnalysisState",
    "PrintFileState",
    "PrintabilityMetrics",
    "PrintabilityReport",
    "SubworkflowStatus",
    "SessionSnapshot",
    "SessionStatus",
    "ThreeDPrintAgent",
    "create_agent",
    "CalibrationError",
    "CalibrationInspection",
    "CalibrationLimits",
    "CalibrationReport",
    "CalibrationResult",
    "ColorAssignment",
    "ColorMapping",
    "InventoryColor",
    "SourceColor",
    "ColorMatchAssignment",
    "ColorMatchResponse",
    "calibrate_3mf",
    "inspect_3mf",
    "geometry_only_3mf",
    "FilamentColorMapping",
    "FilamentColorRecord",
    "FilamentInventoryRepository",
    "InventoryConfigurationError",
    "InventoryDataError",
]
